FROM node:alpine
WORKDIR '/app'

COPY --chown=node:node package.json .

RUN cd /app && npm install

RUN mkdir node_modules/.cache && chmod -R 777 node_modules/.cache

RUN chown -R node.node /app/node_modules

COPY --chown=node:node . .

USER node

CMD ["npm", "start"]

