name: Docker Image CI and Deploy to AWS EB

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the client image
        run: docker build -t hilare/react-test -f ./client/Dockerfile.dev ./client

      - name: Test client
        run: docker run hilare/react-test npm test -- --coverage

      - name: Build images in subdirectories
        run: |
          docker build -t hilare/multi-client ./client
          docker build -t hilare/multi-nginx ./nginx
          docker build -t hilare/multi-server ./server
          docker build -t hilare/multi-worker ./worker

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
