name: Docker Image CI and Deploy to AWS EB

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Environment variables

jobs:
  push-image-to-docker-hub: # job name
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code or latest repo
        uses: actions/checkout@v3

      - name: Build the client image
        run: docker build -t hilare/react-test -f ./client/Dockerfile.dev ./client

      - name: Test client
        run: docker run -e CI=true hilare/react-test npm test

      - name: docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin

      - name: Build docker client
        run: docker build -t hilare/multi-client ./client

      - name: Build nginx
        run: docker build -t hilare/multi-nginx ./nginx

      - name: Build server docker image
        run: docker build -t hilare/multi-server ./server

      - name: Build worker docker image
        run: docker build -t hilare/multi-worker ./worker

      - name: Push docker images
        run: |
          docker push hilare/multi-client
          docker push hilare/multi-nginx
          docker push hilare/multi-server
          docker push hilare/multi-worker